name: Deploy web app to Azure Static Web Apps

on:
  push:
    branches: [ "main" ]

env:
  APP_LOCATION: "/src" # Angular source root
  API_LOCATION: "" # No API
  APP_ARTIFACT_LOCATION: "dist/devdaniels-portfolio" # Angular build output

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: npm ci
      - name: Build Angular app
        run: npm run build -- --output-path ${{ env.APP_ARTIFACT_LOCATION }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
