name: Angular Build & Deploy to Azure Static Web App

on:
  push:
    branches: [ "main" ]

env:
  APP_LOCATION: "/" # Angular source root
  API_LOCATION: "" # No API
  APP_ARTIFACT_LOCATION: "dist/devdaniels-portfolio" # Angular build output

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js (ensure version >= 22.12)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=22.12'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Angular project
      - name: Build Angular
        run: npm run build --prod

      # Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
